### ISSUE TITLE
Fix node engine due to the usage of async/await

### ISSUE THREAD

**Issue by StarpTech** [alex-ppg/fastify-cockroachdb#2]
As titled.

**Comment by alex-ppg** [comment]
Could you elaborate? If this relates to the CI script, I fixed the Docker image to be the latest version CircleCI has up.

**Comment by StarpTech** [comment]
Hi, no I'm missing the property

```
  "engines": {
    "node": ">=8"
  },
```

in the package.json

**Comment by alex-ppg** [comment]
Fixed in latest commit and `npm publish`, I wasn't aware of that property for `package.json`, thanks!
